### PR TITLE
add default data file

### PR DESCRIPTION
**Pull request by yangjie-msft**
add a default data file for use as the base line policy. all download are allowed. all signing should be validated unless signing info is not provided which is mandatory.
Test Result:

Download rule
"extensions_to_download": {
"test1": {
"downloadAllowed": true,
"signingInfo": {
"extensionSigned": false
}
},
"test2": {
"downloadAllowed": true,
"signingInfo": {
"extensionSigned": true
}
},
"test3": {
"downloadAllowed": true,
"signingInfo": {
"extensionSigned": false
}
},
"test4": {
"downloadAllowed": true
}
},
all download are allowed.
signing rule: we require when querying the signing rule, signing information needs to be provide: whether the extension is signed or not. if it is not provided, the signing validation will be false (test 4)
"extensions_validated": {
"test1": {
"allowListOnly": false,
"signingInfo": {
"extensionSigned": false
},
"signingRules": {
"extensionSigned": false,
"signingDetails": {}
},
"signingValidated": true,
"uninstallAllowed": true,
"updateAllowed": true
},
"test2": {
"allowListOnly": false,
"signingInfo": {
"extensionSigned": true
},
"signingRules": {
"extensionSigned": false,
"signingDetails": {}
},
"signingValidated": true,
"uninstallAllowed": true,
"updateAllowed": true
},
"test3": {
"allowListOnly": false,
"signingInfo": {
"extensionSigned": false
},
"signingRules": {
"extensionSigned": false,
"signingDetails": {}
},
"signingValidated": true,
"uninstallAllowed": true,
"updateAllowed": true
},
"test4": {
"allowListOnly": false,
"signingInfo": {},
"signingRules": {
"extensionSigned": false,
"signingDetails": {}
},
"signingValidated": false,
"uninstallAllowed": true,
"updateAllowed": true
}
},

### CODE REVIEW

**Comment by mgunnala** [comment]
Can you clean up the unused sample data files in examples/extension_list, as a part of this PR?

**Comment by mgunnala** [comment]
Why is the signing information required, if the default data isn't enforcing signing?

**Comment by yangjie-msft** [comment]
> Can you clean up the unused sample data files in examples/extension_list, as a part of this PR?

I will clean it up after in the agent code we don't need to use them anymore. currently we still need them for demo purpose. After migrating to the new format, I will clean them up. I will also restructure the directories so it is more clean: 
TASK 27905632

**Comment by yangjie-msft** [comment]
> Why is the signing information required, if the default data isn't enforcing signing?

regardless of the policy, when you actually do the query, the signinginfo should be provided (currently it is extensigned true or false). That's why signingInfo actually will always be present.

**Review by mgunnala — APPROVED** [review]

**Pull request merged**
